# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVvklFNAlykaoxz4LEPKaDbDlGGuk5DX
"""

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup

# 設定 Chrome 無頭模式
options = Options()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.binary_location = '/usr/bin/google-chrome'

# 啟動 Selenium
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# 開啟目標網頁
url = "https://csie.asia.edu.tw/zh_tw/TeacherIntroduction/Full_time_professor"
driver.get(url)

# 等待內容載入
WebDriverWait(driver, 10).until(EC.presence_of_all_elements_located((By.CLASS_NAME, "i-member-item")))

# 擷取網頁內容
soup = BeautifulSoup(driver.page_source, "html.parser")
professors = soup.select(".i-member-item")

# 開啟檔案準備寫入
with open("professors.txt", "w", encoding="utf-8") as f:
    for prof in professors:
        # 姓名
        name_tag = prof.select_one(".member-data-value-name a")
        name = name_tag.text.strip() if name_tag else "未知姓名"

        # 研究領域
        field_tag = prof.select_one(".member-data-value-7")
        field = field_tag.text.strip() if field_tag else "無資料"

        # 輸出與存檔
        output = f"👨‍🏫 姓名：{name}\n🔬 專長：{field}\n{'-'*40}\n"
        print(output)
        f.write(output)

driver.quit()

# 安裝 Chrome 和 ChromeDriver
!apt-get update
!apt-get install -y wget unzip
!wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
!dpkg -i google-chrome-stable_current_amd64.deb || apt-get -fy install

# 安裝 Selenium 所需套件
!pip install selenium webdriver-manager bs4

# 寫爬蟲
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup

# 設定 Chrome 選項（無頭模式）
options = Options()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.binary_location = '/usr/bin/google-chrome'

# 啟動 driver
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# 前往網頁
url = "https://csie.asia.edu.tw/zh_tw/TeacherIntroduction/Full_time_faculty"
driver.get(url)

# 取得 HTML 並解析
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")
print(soup.prettify())
professors = soup.select('.i-member')



# 關閉瀏覽器
driver.quit()